const cloud = require('../../services/cloud');
const media = require('../../services/resource-media');
const categories = [{ id: 'opportunity', label: '机会' }, { id: 'news', label: '行业资讯' }, { id: 'knowledge', label: '知识库' }, { id: 'recap', label: '活动回顾' }];
const empty = { title: '', summary: '', category: 'knowledge', content: '', sourceLabel: '', sourceUrl: '', coverFileId: '', blocks: [] };
const plainBlock = block => block.type === 'image' ? { type: 'image', fileId: block.fileId } : { type: block.type, text: block.text || '' };
function editableBlocks(blocks, legacyContent) { const source = Array.isArray(blocks) && blocks.length ? blocks : legacyContent ? [{ type: 'paragraph', text: legacyContent }] : []; return source.map(plainBlock); }
Page({
  data: { status: 'loading', form: empty, categories, version: 0, resourceStatus: 'draft', busy: false, uploading: false, dirty: false, error: '', message: '', coverPreviewUrl: '' },
  onLoad(options) { this._active = true; this._existing = !!(options && options.id); this._id = this._existing ? options.id : 's-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 12); return this.load(); },
  onUnload() { this._active = false; },
  canEdit() { return !this.data.busy && !this.data.uploading && this.data.resourceStatus === 'draft'; },
  async hydrateImages(form) { const fileIds = [form.coverFileId].concat(form.blocks.filter(block => block.type === 'image').map(block => block.fileId)); const urls = await media.getTempFileUrls(fileIds); if (!this._active) return; const blocks = form.blocks.map(block => block.type === 'image' ? Object.assign({}, block, { previewUrl: urls[block.fileId] || '' }) : block); this.setData({ form: Object.assign({}, form, { blocks }), coverPreviewUrl: urls[form.coverFileId] || '' }); },
  async load() { this.setData({ status: 'loading', error: '' }); try { const identity = await cloud.call('identity'); if (identity.role !== 'admin') throw new Error('无管理权限'); const resource = this._existing ? await cloud.call('getManagedResource', { id: this._id }) : null; if (this._existing && !resource) throw new Error('资源不存在'); if (resource) { const form = { title: resource.title || '', summary: resource.summary || '', category: resource.category || 'knowledge', content: '', sourceLabel: resource.sourceLabel || '', sourceUrl: resource.sourceUrl || '', coverFileId: resource.coverFileId || '', blocks: editableBlocks(resource.blocks, resource.content) }; this.setData({ form, version: resource.version, resourceStatus: resource.status, dirty: false }); await this.hydrateImages(form); } if (this._active) this.setData({ status: 'ready' }); } catch (error) { if (this._active) this.setData({ status: 'error', error: error.message }); } },
  input(event) { const key = event.currentTarget.dataset.field; if (!Object.prototype.hasOwnProperty.call(empty, key) || !this.canEdit()) return; this.setData({ form: Object.assign({}, this.data.form, { [key]: event.detail.value }), dirty: true, message: '', error: '' }); },
  selectCategory(event) { const category = event.currentTarget.dataset.id; if (!categories.some(item => item.id === category) || !this.canEdit()) return; this.setData({ form: Object.assign({}, this.data.form, { category }), dirty: true, message: '', error: '' }); },
  updateBlocks(blocks) { this.setData({ form: Object.assign({}, this.data.form, { blocks }), dirty: true, message: '', error: '' }); },
  blockInput(event) { if (!this.canEdit()) return; const index = Number(event.currentTarget.dataset.index); if (!Number.isSafeInteger(index) || !this.data.form.blocks[index]) return; const blocks = this.data.form.blocks.slice(); blocks[index] = Object.assign({}, blocks[index], { text: event.detail.value }); this.updateBlocks(blocks); },
  addTextBlock(event) { if (!this.canEdit()) return; const type = event.currentTarget.dataset.type; if (!['heading', 'paragraph', 'quote'].includes(type) || this.data.form.blocks.length >= 32) return; this.updateBlocks(this.data.form.blocks.concat({ type, text: '' })); },
  async addImageBlock() { if (!this.canEdit()) return; if (this.data.form.blocks.filter(block => block.type === 'image').length >= 6) { wx.showToast({ title: '正文最多插入 6 张图片', icon: 'none' }); return; } this.setData({ uploading: true, error: '', message: '' }); try { const fileId = await media.pickAndUploadImage(); const urls = await media.getTempFileUrls([fileId]); if (this._active) this.updateBlocks(this.data.form.blocks.concat({ type: 'image', fileId, previewUrl: urls[fileId] || '' })); } catch (error) { if (this._active && error.message !== '已取消选择图片') this.setData({ error: error.message || '图片上传失败' }); } finally { if (this._active) this.setData({ uploading: false }); } },
  removeBlock(event) { if (!this.canEdit()) return; const index = Number(event.currentTarget.dataset.index); if (!Number.isSafeInteger(index)) return; this.updateBlocks(this.data.form.blocks.filter((_, current) => current !== index)); },
  moveBlock(event) { if (!this.canEdit()) return; const index = Number(event.currentTarget.dataset.index); const delta = Number(event.currentTarget.dataset.delta); const target = index + delta; const blocks = this.data.form.blocks.slice(); if (!Number.isSafeInteger(index) || !Number.isSafeInteger(delta) || !blocks[index] || !blocks[target]) return; [blocks[index], blocks[target]] = [blocks[target], blocks[index]]; this.updateBlocks(blocks); },
  async chooseCover() { if (!this.canEdit()) return; this.setData({ uploading: true, error: '', message: '' }); try { const coverFileId = await media.pickAndUploadImage(); const urls = await media.getTempFileUrls([coverFileId]); if (this._active) this.setData({ form: Object.assign({}, this.data.form, { coverFileId }), coverPreviewUrl: urls[coverFileId] || '', dirty: true }); } catch (error) { if (this._active && error.message !== '已取消选择图片') this.setData({ error: error.message || '封面上传失败' }); } finally { if (this._active) this.setData({ uploading: false }); } },
  clearCover() { if (!this.canEdit()) return; this.setData({ form: Object.assign({}, this.data.form, { coverFileId: '' }), coverPreviewUrl: '', dirty: true, message: '' }); },
  payload() { return Object.assign({}, this.data.form, { blocks: this.data.form.blocks.map(plainBlock) }); },
  async save() { if (!this.canEdit()) return; this.setData({ busy: true, error: '', message: '' }); try { const saved = await cloud.call('saveResourceDraft', { id: this._id, version: this.data.version, resource: this.payload() }); const form = { title: saved.title || '', summary: saved.summary || '', category: saved.category || 'knowledge', content: '', sourceLabel: saved.sourceLabel || '', sourceUrl: saved.sourceUrl || '', coverFileId: saved.coverFileId || '', blocks: editableBlocks(saved.blocks, saved.content) }; if (this._active) { this.setData({ form, version: saved.version, dirty: false, message: '草稿已保存，成员暂不可见' }); await this.hydrateImages(form); } } catch (error) { if (this._active) this.setData({ error: error.message }); } finally { if (this._active) this.setData({ busy: false }); } },
  publish() { if (!this.canEdit() || this.data.dirty || !this.data.version) return; wx.showModal({ title: '发布资源', content: '发布后成员可见。请确认图片、正文和来源信息均可公开展示。是否继续？', success: async result => { if (!result.confirm || !this._active) return; this.setData({ busy: true, error: '', message: '' }); try { const saved = await cloud.call('publishResource', { id: this._id, version: this.data.version }); if (this._active) this.setData({ version: saved.version, resourceStatus: saved.status, message: '资源已发布' }); } catch (error) { if (this._active) this.setData({ error: error.message }); } finally { if (this._active) this.setData({ busy: false }); } }}); }
});
